# Example simulation for integrating veins (http://veins.car2x.org/) with Simu5G
# 
# Requirements:
#       You need to enable the feature "Simu5G Cars" for this simulation
#       (Project->Properties->OMNeT++->Project Features)
#
#       You need to import the "veins" project and its subproject
#       "veins_inet" in your workspace.
[General]
cmdenv-express-mode = true
#cmdenv-express-setup = "mpiexec -n 4 sleep infinity"
# parallel-simulation = true
# parsim-num-partitions = 4
# parsim-communications-class = "cMPICommunications"
# parsim-synchronization-class = "cNullMessageProtocol"
# parsim-debug=false
# *.gNodeB[1..500]**.partition-id=0
# *.gNodeB[501..1000]**.partition-id=1
# *.gNodeB[1001..1355]**.partition-id=2
# **.partition-id=3

**.tolerateMaxDistViolation_ = true


cmdenv-autoflush = true
cmdenv-status-frequency = 1s
image-path = ../../images
network = simu5g.simulations.NR.cars_turin.Highway

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 7000s

**.sctp.**.scalar-recording = true
**.sctp.**.vector-recording = true
**.routingRecorder.enabled = false

*.playgroundSizeX = 20000m
*.playgroundSizeY = 20000m
*.playgroundSizeZ = 50m


*.annotations.draw = true
#Obstaculos
*.obstacles.obstacles = xmldoc("config.xml", "//AnalogueModel[@type='SimpleObstacleShadowing']/obstacles")

##########################################################
#            VeinsManager parameters                     #
##########################################################
*.veinsManager.host = "localhost"       # if traci-launchd runs on localhost
*.veinsManager.moduleType = "simu5g.nodes.cars.NRCar"
*.veinsManager.moduleName = "car"
*.veinsManager.launchConfig = xmldoc("turin.launchd.xml")
*.veinsManager.updateInterval = 0.1s

##########################################################
#                      Mobility                          #
##########################################################
*.car[*].mobility.typename = "VeinsInetMobility"


##########################################################
#          Mobile network specific parameters            #
##########################################################

# Number of Resource Blocks
**.numBands = 25 

# Transmission Power
**.ueTxPower = 26
**.eNodeBTxPower = 46

# Enable dynamic association of UEs (based on best SINR)
*.car[*].cellularNic.nrPhy.dynamicCellAssociation = true
*.car[*].masterId = 0     # ignored if dynamic association is disabled
*.car[*].macCellId = 0    # ignored if dynamic association is disabled
*.car[*].nrMasterId = 1     # ignored if dynamic association is disabled
*.car[*].nrMacCellId = 1    # ignored if dynamic association is disabled

# eNodeB configuration
**.gNodeB1.macCellId = 1
**.gNodeB1.macNodeId = 1
**.gNodeB2.macCellId = 2
**.gNodeB2.macNodeId = 2
**.gNodeB3.macCellId = 3
**.gNodeB3.macNodeId = 3
**.gNodeB4.macCellId = 4
**.gNodeB4.macNodeId = 4
**.gNodeB5.macCellId = 5
**.gNodeB5.macNodeId = 5
**.gNodeB6.macCellId = 6
**.gNodeB6.macNodeId = 6
**.gNodeB7.macCellId = 7
**.gNodeB7.macNodeId = 7
**.gNodeB8.macCellId = 8
**.gNodeB8.macNodeId = 8
**.gNodeB9.macCellId = 9
**.gNodeB9.macNodeId = 9
**.gNodeB10.macCellId = 10
**.gNodeB10.macNodeId = 10
**.gNodeB11.macCellId = 11
**.gNodeB11.macNodeId = 11
**.gNodeB12.macCellId = 12
**.gNodeB12.macNodeId = 12
**.gNodeB13.macCellId = 13
**.gNodeB13.macNodeId = 13
**.gNodeB14.macCellId = 14
**.gNodeB14.macNodeId = 14
**.gNodeB15.macCellId = 15
**.gNodeB15.macNodeId = 15
**.gNodeB16.macCellId = 16
**.gNodeB16.macNodeId = 16
**.gNodeB17.macCellId = 17
**.gNodeB17.macNodeId = 17
**.gNodeB18.macCellId = 18
**.gNodeB18.macNodeId = 18
**.gNodeB19.macCellId = 19
**.gNodeB19.macNodeId = 19
**.gNodeB20.macCellId = 20
**.gNodeB20.macNodeId = 20
**.gNodeB21.macCellId = 21
**.gNodeB21.macNodeId = 21
**.gNodeB22.macCellId = 22
**.gNodeB22.macNodeId = 22
**.gNodeB23.macCellId = 23
**.gNodeB23.macNodeId = 23
**.gNodeB24.macCellId = 24
**.gNodeB24.macNodeId = 24
**.gNodeB25.macCellId = 25
**.gNodeB25.macNodeId = 25
**.gNodeB26.macCellId = 26
**.gNodeB26.macNodeId = 26
**.gNodeB27.macCellId = 27
**.gNodeB27.macNodeId = 27
**.gNodeB28.macCellId = 28
**.gNodeB28.macNodeId = 28
**.gNodeB29.macCellId = 29
**.gNodeB29.macNodeId = 29
**.gNodeB30.macCellId = 30
**.gNodeB30.macNodeId = 30
**.gNodeB31.macCellId = 31
**.gNodeB31.macNodeId = 31
**.gNodeB32.macCellId = 32
**.gNodeB32.macNodeId = 32
**.gNodeB33.macCellId = 33
**.gNodeB33.macNodeId = 33
**.gNodeB34.macCellId = 34
**.gNodeB34.macNodeId = 34
**.gNodeB35.macCellId = 35
**.gNodeB35.macNodeId = 35
**.gNodeB36.macCellId = 36
**.gNodeB36.macNodeId = 36
**.gNodeB37.macCellId = 37
**.gNodeB37.macNodeId = 37
**.gNodeB38.macCellId = 38
**.gNodeB38.macNodeId = 38
**.gNodeB39.macCellId = 39
**.gNodeB39.macNodeId = 39
**.gNodeB40.macCellId = 40
**.gNodeB40.macNodeId = 40
**.gNodeB41.macCellId = 41
**.gNodeB41.macNodeId = 41
**.gNodeB42.macCellId = 42
**.gNodeB42.macNodeId = 42
**.gNodeB43.macCellId = 43
**.gNodeB43.macNodeId = 43
**.gNodeB44.macCellId = 44
**.gNodeB44.macNodeId = 44
**.gNodeB45.macCellId = 45
**.gNodeB45.macNodeId = 45
**.gNodeB46.macCellId = 46
**.gNodeB46.macNodeId = 46
**.gNodeB47.macCellId = 47
**.gNodeB47.macNodeId = 47
**.gNodeB48.macCellId = 48
**.gNodeB48.macNodeId = 48
**.gNodeB49.macCellId = 49
**.gNodeB49.macNodeId = 49
**.gNodeB50.macCellId = 50
**.gNodeB50.macNodeId = 50
**.gNodeB51.macCellId = 51
**.gNodeB51.macNodeId = 51
**.gNodeB52.macCellId = 52
**.gNodeB52.macNodeId = 52
**.gNodeB53.macCellId = 53
**.gNodeB53.macNodeId = 53
**.gNodeB54.macCellId = 54
**.gNodeB54.macNodeId = 54
**.gNodeB55.macCellId = 55
**.gNodeB55.macNodeId = 55
**.gNodeB56.macCellId = 56
**.gNodeB56.macNodeId = 56
**.gNodeB57.macCellId = 57
**.gNodeB57.macNodeId = 57
**.gNodeB58.macCellId = 58
**.gNodeB58.macNodeId = 58
**.gNodeB59.macCellId = 59
**.gNodeB59.macNodeId = 59
**.gNodeB60.macCellId = 60
**.gNodeB60.macNodeId = 60
**.gNodeB61.macCellId = 61
**.gNodeB61.macNodeId = 61
**.gNodeB62.macCellId = 62
**.gNodeB62.macNodeId = 62
**.gNodeB63.macCellId = 63
**.gNodeB63.macNodeId = 63
**.gNodeB64.macCellId = 64
**.gNodeB64.macNodeId = 64
**.gNodeB65.macCellId = 65
**.gNodeB65.macNodeId = 65
**.gNodeB66.macCellId = 66
**.gNodeB66.macNodeId = 66
**.gNodeB67.macCellId = 67
**.gNodeB67.macNodeId = 67
**.gNodeB68.macCellId = 68
**.gNodeB68.macNodeId = 68
**.gNodeB69.macCellId = 69
**.gNodeB69.macNodeId = 69
**.gNodeB70.macCellId = 70
**.gNodeB70.macNodeId = 70
**.gNodeB71.macCellId = 71
**.gNodeB71.macNodeId = 71
**.gNodeB72.macCellId = 72
**.gNodeB72.macNodeId = 72
**.gNodeB73.macCellId = 73
**.gNodeB73.macNodeId = 73
**.gNodeB74.macCellId = 74
**.gNodeB74.macNodeId = 74
**.gNodeB75.macCellId = 75
**.gNodeB75.macNodeId = 75
**.gNodeB76.macCellId = 76
**.gNodeB76.macNodeId = 76
**.gNodeB77.macCellId = 77
**.gNodeB77.macNodeId = 77
**.gNodeB78.macCellId = 78
**.gNodeB78.macNodeId = 78
**.gNodeB79.macCellId = 79
**.gNodeB79.macNodeId = 79
**.gNodeB80.macCellId = 80
**.gNodeB80.macNodeId = 80
**.gNodeB81.macCellId = 81
**.gNodeB81.macNodeId = 81
**.gNodeB82.macCellId = 82
**.gNodeB82.macNodeId = 82
**.gNodeB83.macCellId = 83
**.gNodeB83.macNodeId = 83
**.gNodeB84.macCellId = 84
**.gNodeB84.macNodeId = 84
**.gNodeB85.macCellId = 85
**.gNodeB85.macNodeId = 85
**.gNodeB86.macCellId = 86
**.gNodeB86.macNodeId = 86
**.gNodeB87.macCellId = 87
**.gNodeB87.macNodeId = 87
**.gNodeB88.macCellId = 88
**.gNodeB88.macNodeId = 88
**.gNodeB89.macCellId = 89
**.gNodeB89.macNodeId = 89
**.gNodeB90.macCellId = 90
**.gNodeB90.macNodeId = 90
**.gNodeB91.macCellId = 91
**.gNodeB91.macNodeId = 91
**.gNodeB92.macCellId = 92
**.gNodeB92.macNodeId = 92
**.gNodeB93.macCellId = 93
**.gNodeB93.macNodeId = 93
**.gNodeB94.macCellId = 94
**.gNodeB94.macNodeId = 94
**.gNodeB95.macCellId = 95
**.gNodeB95.macNodeId = 95
**.gNodeB96.macCellId = 96
**.gNodeB96.macNodeId = 96
**.gNodeB97.macCellId = 97
**.gNodeB97.macNodeId = 97
**.gNodeB98.macCellId = 98
**.gNodeB98.macNodeId = 98
**.gNodeB99.macCellId = 99
**.gNodeB99.macNodeId = 99
**.gNodeB100.macCellId = 100
**.gNodeB100.macNodeId = 100
**.gNodeB101.macCellId = 101
**.gNodeB101.macNodeId = 101
**.gNodeB102.macCellId = 102
**.gNodeB102.macNodeId = 102
**.gNodeB103.macCellId = 103
**.gNodeB103.macNodeId = 103
**.gNodeB104.macCellId = 104
**.gNodeB104.macNodeId = 104
**.gNodeB105.macCellId = 105
**.gNodeB105.macNodeId = 105
**.gNodeB106.macCellId = 106
**.gNodeB106.macNodeId = 106
**.gNodeB107.macCellId = 107
**.gNodeB107.macNodeId = 107
**.gNodeB108.macCellId = 108
**.gNodeB108.macNodeId = 108
**.gNodeB109.macCellId = 109
**.gNodeB109.macNodeId = 109
**.gNodeB110.macCellId = 110
**.gNodeB110.macNodeId = 110
**.gNodeB111.macCellId = 111
**.gNodeB111.macNodeId = 111
**.gNodeB112.macCellId = 112
**.gNodeB112.macNodeId = 112
**.gNodeB113.macCellId = 113
**.gNodeB113.macNodeId = 113
**.gNodeB114.macCellId = 114
**.gNodeB114.macNodeId = 114
**.gNodeB115.macCellId = 115
**.gNodeB115.macNodeId = 115
**.gNodeB116.macCellId = 116
**.gNodeB116.macNodeId = 116
**.gNodeB117.macCellId = 117
**.gNodeB117.macNodeId = 117
**.gNodeB118.macCellId = 118
**.gNodeB118.macNodeId = 118
**.gNodeB119.macCellId = 119
**.gNodeB119.macNodeId = 119
**.gNodeB120.macCellId = 120
**.gNodeB120.macNodeId = 120
**.gNodeB121.macCellId = 121
**.gNodeB121.macNodeId = 121
**.gNodeB122.macCellId = 122
**.gNodeB122.macNodeId = 122
**.gNodeB123.macCellId = 123
**.gNodeB123.macNodeId = 123
**.gNodeB124.macCellId = 124
**.gNodeB124.macNodeId = 124
**.gNodeB125.macCellId = 125
**.gNodeB125.macNodeId = 125
**.gNodeB126.macCellId = 126
**.gNodeB126.macNodeId = 126
**.gNodeB127.macCellId = 127
**.gNodeB127.macNodeId = 127
**.gNodeB128.macCellId = 128
**.gNodeB128.macNodeId = 128
**.gNodeB129.macCellId = 129
**.gNodeB129.macNodeId = 129
**.gNodeB130.macCellId = 130
**.gNodeB130.macNodeId = 130
**.gNodeB131.macCellId = 131
**.gNodeB131.macNodeId = 131
**.gNodeB132.macCellId = 132
**.gNodeB132.macNodeId = 132
**.gNodeB133.macCellId = 133
**.gNodeB133.macNodeId = 133
**.gNodeB134.macCellId = 134
**.gNodeB134.macNodeId = 134
**.gNodeB135.macCellId = 135
**.gNodeB135.macNodeId = 135
**.gNodeB136.macCellId = 136
**.gNodeB136.macNodeId = 136
**.gNodeB137.macCellId = 137
**.gNodeB137.macNodeId = 137
**.gNodeB138.macCellId = 138
**.gNodeB138.macNodeId = 138
**.gNodeB139.macCellId = 139
**.gNodeB139.macNodeId = 139
**.gNodeB140.macCellId = 140
**.gNodeB140.macNodeId = 140
**.gNodeB141.macCellId = 141
**.gNodeB141.macNodeId = 141
**.gNodeB142.macCellId = 142
**.gNodeB142.macNodeId = 142
**.gNodeB143.macCellId = 143
**.gNodeB143.macNodeId = 143
**.gNodeB144.macCellId = 144
**.gNodeB144.macNodeId = 144
**.gNodeB145.macCellId = 145
**.gNodeB145.macNodeId = 145
**.gNodeB146.macCellId = 146
**.gNodeB146.macNodeId = 146
**.gNodeB147.macCellId = 147
**.gNodeB147.macNodeId = 147
**.gNodeB148.macCellId = 148
**.gNodeB148.macNodeId = 148
**.gNodeB149.macCellId = 149
**.gNodeB149.macNodeId = 149
**.gNodeB150.macCellId = 150
**.gNodeB150.macNodeId = 150
**.gNodeB151.macCellId = 151
**.gNodeB151.macNodeId = 151
**.gNodeB152.macCellId = 152
**.gNodeB152.macNodeId = 152
**.gNodeB153.macCellId = 153
**.gNodeB153.macNodeId = 153
**.gNodeB154.macCellId = 154
**.gNodeB154.macNodeId = 154
**.gNodeB155.macCellId = 155
**.gNodeB155.macNodeId = 155
**.gNodeB156.macCellId = 156
**.gNodeB156.macNodeId = 156
**.gNodeB157.macCellId = 157
**.gNodeB157.macNodeId = 157
**.gNodeB158.macCellId = 158
**.gNodeB158.macNodeId = 158
**.gNodeB159.macCellId = 159
**.gNodeB159.macNodeId = 159
**.gNodeB160.macCellId = 160
**.gNodeB160.macNodeId = 160
**.gNodeB161.macCellId = 161
**.gNodeB161.macNodeId = 161
**.gNodeB162.macCellId = 162
**.gNodeB162.macNodeId = 162
**.gNodeB163.macCellId = 163
**.gNodeB163.macNodeId = 163
**.gNodeB164.macCellId = 164
**.gNodeB164.macNodeId = 164
**.gNodeB165.macCellId = 165
**.gNodeB165.macNodeId = 165
**.gNodeB166.macCellId = 166
**.gNodeB166.macNodeId = 166
**.gNodeB167.macCellId = 167
**.gNodeB167.macNodeId = 167
**.gNodeB168.macCellId = 168
**.gNodeB168.macNodeId = 168
**.gNodeB169.macCellId = 169
**.gNodeB169.macNodeId = 169
**.gNodeB170.macCellId = 170
**.gNodeB170.macNodeId = 170
**.gNodeB171.macCellId = 171
**.gNodeB171.macNodeId = 171
**.gNodeB172.macCellId = 172
**.gNodeB172.macNodeId = 172
**.gNodeB173.macCellId = 173
**.gNodeB173.macNodeId = 173
**.gNodeB174.macCellId = 174
**.gNodeB174.macNodeId = 174
**.gNodeB175.macCellId = 175
**.gNodeB175.macNodeId = 175
**.gNodeB176.macCellId = 176
**.gNodeB176.macNodeId = 176
**.gNodeB177.macCellId = 177
**.gNodeB177.macNodeId = 177
**.gNodeB178.macCellId = 178
**.gNodeB178.macNodeId = 178
**.gNodeB179.macCellId = 179
**.gNodeB179.macNodeId = 179
**.gNodeB180.macCellId = 180
**.gNodeB180.macNodeId = 180
**.gNodeB181.macCellId = 181
**.gNodeB181.macNodeId = 181
**.gNodeB182.macCellId = 182
**.gNodeB182.macNodeId = 182
**.gNodeB183.macCellId = 183
**.gNodeB183.macNodeId = 183
**.gNodeB184.macCellId = 184
**.gNodeB184.macNodeId = 184
**.gNodeB185.macCellId = 185
**.gNodeB185.macNodeId = 185
**.gNodeB186.macCellId = 186
**.gNodeB186.macNodeId = 186
**.gNodeB187.macCellId = 187
**.gNodeB187.macNodeId = 187
**.gNodeB188.macCellId = 188
**.gNodeB188.macNodeId = 188
**.gNodeB189.macCellId = 189
**.gNodeB189.macNodeId = 189
**.gNodeB190.macCellId = 190
**.gNodeB190.macNodeId = 190
**.gNodeB191.macCellId = 191
**.gNodeB191.macNodeId = 191
**.gNodeB192.macCellId = 192
**.gNodeB192.macNodeId = 192
**.gNodeB193.macCellId = 193
**.gNodeB193.macNodeId = 193
**.gNodeB194.macCellId = 194
**.gNodeB194.macNodeId = 194
**.gNodeB195.macCellId = 195
**.gNodeB195.macNodeId = 195
**.gNodeB196.macCellId = 196
**.gNodeB196.macNodeId = 196
**.gNodeB197.macCellId = 197
**.gNodeB197.macNodeId = 197
**.gNodeB198.macCellId = 198
**.gNodeB198.macNodeId = 198
**.gNodeB199.macCellId = 199
**.gNodeB199.macNodeId = 199
**.gNodeB200.macCellId = 200
**.gNodeB200.macNodeId = 200
**.gNodeB201.macCellId = 201
**.gNodeB201.macNodeId = 201
**.gNodeB202.macCellId = 202
**.gNodeB202.macNodeId = 202
**.gNodeB203.macCellId = 203
**.gNodeB203.macNodeId = 203
**.gNodeB204.macCellId = 204
**.gNodeB204.macNodeId = 204
**.gNodeB205.macCellId = 205
**.gNodeB205.macNodeId = 205





# Enable handover
*.car[*].cellularNic.nrPhy.enableHandover = true
*.gNodeB*.cellularNic.phy.enableHandover = true
*.gNodeB*.cellularNic.phy.handoverLatency = 50ms
*.gNodeB*.cellInfo.broadcastMessageInterval = 1s # eNB will sends broadcast triggers every second

# X2 and SCTP configuration
*.gNodeB*.numX2Apps = 0    # one x2App per peering eNodeB
#*.gNodeB*.x2App[*].server.localPort = 5000 + ancestorIndex(1) # Server ports (x2App[0]=5000, x2App[1]=5001, ...)
#*.gNodeB1.x2App[0].client.connectAddress = "gNodeB2%x2ppp0" 
#*.gNodeB2.x2App[0].client.connectAddress = "gNodeB1%x2ppp0" 
#**.sctp.nagleEnabled = false         # if true, transmission of small packets will be delayed on the X2
#**.sctp.enableHeartbeats = false


# ----------------------------------------------------------------------------- #
# Config "VoIP-Uplink"
#
[Config VoIP-UL]

##########################################################
#                    App Layer                           #
##########################################################
*.server.numApps = 10
*.server.app[*].typename = "VoIPReceiver"
*.server.app[*].localPort = 3000 + ancestorIndex(0) 

#*.car[*].numApps = 1
#*.car[*].app[0].typename = "VoIPSender"
#*.car[*].app[0].destAddress = "server"
#*.car[*].app[0].destPort = 3000 + ancestorIndex(1)

#isoto
*.car[*].numApps = 2
*.car[*].app[0].typename = "Navigator"
*.car[*].app[1].typename = "VoIPSender"
*.car[*].app[1].destAddress = "server"
*.car[*].app[1].destPort = 3000 + ancestorIndex(1)


# ----------------------------------------------------------------------------- #
# Config "sNavigator"
#
[Config sNavigator]

##########################################################
#                    App Layer                           #
##########################################################
*.server.numApps = 10
*.server.app[*].typename = "SNavigatorServer2"
*.server.app[*].localPort = 3000 + ancestorIndex(0)
*.server.app[*].destPort = 6000 + ancestorIndex(0)
*.server.app[*].destAddress = "car[" + string(ancestorIndex(0)) + "]"
*.server.app[*].startTime = 0.05s

*.server.app[*].mapName = "turin"


*.car[*].numApps = 1
*.car[*].app[0].typename = "SNavigatorVehicle2"
*.car[*].app[0].localPort = 6000 + ancestorIndex(1)
*.car[*].app[0].destPort = 3000 + ancestorIndex(1)
*.car[*].app[0].destAddress = "server"
*.car[*].app[0].startTime = 0.05s


# ----------------------------------------------------------------------------- #
# Config "VoIP-D2D"
#
# In this configuration, UEs run a VoIP application (using UDP as transport layer protocol)
# They communicate using the D2D link, if they are under the same cell
#
[Config VoIP-D2D]

**.amcMode = "D2D"

# D2D-capable flows are started in D2D mode
*.car[*].cellularNic.d2dInitialMode = true

# --- Select CQI for D2D transmissions --- #
#
# To enable the reporting of CQIs for each D2D link, set the parameter *.gNodeB.cellularNic.phy.enableD2DCqiReporting
# To use fixed CQI, set the parameter **.usePreconfiguredTxParams and select the desired CQI using the parameter **.d2dCqi
*.gNodeB*.cellularNic.nrPhy.enableD2DCqiReporting = true
**.usePreconfiguredTxParams = false

# each vehicle transmits using D2D to the following one 
*.car[*].numApps = 1
*.car[0].app[0].typename = "VoIPSender"
*.car[0].app[0].destAddress = "car[1]"
*.car[1].app[0].typename = "VoIPReceiver"

*.car[2].app[0].typename = "VoIPSender"
*.car[2].app[0].destAddress = "car[3]"
*.car[3].app[0].typename = "VoIPReceiver"

*.car[4].app[0].typename = "VoIPSender"
*.car[4].app[0].destAddress = "car[5]"
*.car[5].app[0].typename = "VoIPReceiver"

*.car[6].app[0].typename = "VoIPSender"
*.car[6].app[0].destAddress = "car[7]"
*.car[7].app[0].typename = "VoIPReceiver"


# ----------------------------------------------------------------------------- #
# Config "D2DMulticast"
#
# In this configuration, vehicles form two groups (vehicles on the same lane are in the same group).
# For each group, the leader vehicle transmits periodic alert messages to following vehicles
#
[Config D2DMulticast]

### Enable D2D for the eNodeB and the UEs involved in direct communications ###
**.amcMode = "D2D"

### Select CQI for D2D transmissions ###
# One-to-Many communications work with fixed CQI values only.
# Set the parameter **.usePreconfiguredTxParams and select the desired CQI using the parameter **.d2dCqi
**.enableD2DCqiReporting = false
**.usePreconfiguredTxParams = true
**.d2dCqi = ${cqi=7}

### Traffic configuration ###
*.car[*].numApps = 1

# --- 1st group: 0 < 1 < 2 < 3 -- #
*.car[0..4].ipv4.configurator.mcastGroups = "224.0.0.10"
# transmitter
*.car[0].app[*].typename = "AlertSender"
*.car[0].app[*].localPort = 3088+ancestorIndex(0) 
*.car[0].app[*].startTime = uniform(0s,0.02s)
*.car[0].app[*].destAddress = "224.0.0.10"          # IP address of the multicast group 
*.car[0].app[*].destPort = 1000
# receivers
*.car[1..3].app[*].typename = "AlertReceiver"
*.car[1..3].app[*].localPort = 1000

# --- 2nd group: 4 < 5 < 6 < 7 -- #
*.car[4..7].ipv4.configurator.mcastGroups = "224.0.0.11"
# transmitter
*.car[4].app[*].typename = "AlertSender"
*.car[4].app[*].localPort = 3088+ancestorIndex(0) 
*.car[4].app[*].startTime = uniform(0s,0.02s)
*.car[4].app[*].destAddress = "224.0.0.11"          # IP address of the multicast group 
*.car[4].app[*].destPort = 1000
# receivers (they must belong to the above multicast group)
*.car[5..7].app[*].typename = "AlertReceiver"
*.car[5..7].app[*].localPort = 1000


